### PR TITLE
Quality of Life Improvements for Development and Publication Workflow

### PR DESCRIPTION
**Pull request by vnphanquang**
Hello all, this PR adds a handful of things with the hope of improving the dev and publication workflow. Please note:

> [!NOTE]
> Everything is just a proposal. Please feel free to reject or comment. I am happy to follow up / drop unwanted changes.

Each commit is well scoped to a particular change so please feel free to review one individual commit at a time. Some notable changes are as follow.

## Development Workflow

https://github.com/evilmartians/harmony/commit/4f3d62156d7c35aadcbb325dce6eb80ebd64ca76 sets up  [lefthook](https://github.com/evilmartians/lefthook) (quite fitting as it is also from @evilmartians), and some explicit fmt rules in `deno.json`. This will help keeping code style consistent going forward.

## Versioning & Publication

https://github.com/evilmartians/harmony/commit/9c98741ba6a1e2ef29e595550850f6de76097782 sets up [changesets](https://github.com/changesets/changesets) for versioning and automatic publication to NPM. I also added to README a reference for a suggested dev & publication workflow.

> [!IMPORTANT]
> The new `changesets` workflow requires 2 updates to the repo settings:
> 1. a `NPM_TOKEN` repo secret, which might already be there judging by the `publish.yml.disabled` workflow. Anyway this token requires sufficient permission, i suggest a "classic" token of "Automation" type from NPM settings.
> 2. update Workflow permissions to allow read&write and create PR. This can be done at https://github.com/evilmartians/harmony/settings/actions right at the two bottom sections.

Additionally, https://github.com/evilmartians/harmony/commit/1419ab0ea8c303830bfed05022ac8bab7efff540 sets up [package provenance](https://github.blog/security/supply-chain-security/introducing-npm-package-provenance/), which should give it a bit more credibility in the npm registry.

## Tests

https://github.com/evilmartians/harmony/commit/376f9e6dbb0d4008bf894c3b97896b7beecccc52 adds a test workflow that triggers by changes to relevant files on `push` or PR to `main`. It also uploads code coverage report and test results to Codecov. The project is simple enough for now that I don't think this is strictly necessary, but I figured while I was at it, might as well set it up anyway. Added via https://github.com/evilmartians/harmony/commit/f5b7352b8e7a7ee49d1f48600489309cc6e89e99 is a badge showing code coverage percentage - helpful as a quick glance indicator of project health.

Happy to remove this out if you think it's unnecessary. Just let me know.

> [!IMPORTANT]
> If you decide to keep the Codecov upload, the new `tests` workflow requires a `CODECOV_TOKEN` which you can get after setting up Codecov for the repo.

## Package Exports

https://github.com/evilmartians/harmony/commit/290fcd91f0c3b70de1e78539b346d7301b008cb1 adds [publint](https://github.com/bluwy/publint) to check against package exports. I also made some changes to the exports, specifically setting package as ESM-first (type: module) since the ecosystem is going that way. Some changes are also based on recommendation from publint: https://publint.dev/@evilmartians/harmony@1.3.0

## Deno 2

Along the way, especially in https://github.com/evilmartians/harmony/commit/7cd13650d8d40e888ffe7924a52f825c7718165d, I updated the dependency strategy to utilize Deno 2 support for [JSR](https://jsr.io/) and Node-compat.

Thanks all.

### CODE REVIEW

**Comment by 11bit** [comment]
Thanks for PR. Overall it looks great! But I'll need some to read it through and setup env vars. It will probably take a couple of days

**Comment by vnphanquang** [comment]
@11bit thanks for checking. Take your time.

**Comment by 11bit** [comment]
Thanks @vnphanquang! This is really helpful! The only thing I changed is removing codecov and test matrix for now

**Comment by vnphanquang** [comment]
Excellent @11bit. Thanks a lot. Looks like the changeset worflow is in order.

FYI the ["Releases" section](https://github.com/evilmartians/harmony/releases) isn't switched on for the repo but if that's by choice please ignore my comment.

**Pull request merged**
