### PR TITLE
Proposal: Declarative Build Strategy with Mustache Template

### PR DESCRIPTION
**Pull request by vnphanquang**
## Description

While I was working on #12 and #14, I noticed that there was an opportunity to utilize a template-based build strategy instead of relying on string manipulation & concatenation as of now. This PR implements that. Please note that it changes the codebase significantly and I hope that doesn't come across as too ignorant. Happy to respect whatever decision you make as code owner.

As for benchmark, this new build strategy does not provide, nor aim at, any improvement over speed...

```
CPU | Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Runtime | Deno 2.1.1 (x86_64-unknown-linux-gnu)

benchmark   time/iter (avg)        iter/s      (min … max)           p75      p99     p995
----------- ----------------------------- --------------------- --------------------------
old build           32.1 ms          31.1 ( 28.9 ms …  35.1 ms)  32.9 ms  35.1 ms  35.1 ms
new build           31.8 ms          31.5 ( 29.4 ms …  33.9 ms)  32.5 ms  33.9 ms  33.9 ms

summary
  old build
     1.01x slower than new build
```

<details>

<summary><strong>View benchmark script</strong></summary>

```typescript
import * as path from 'jsr:@std/path';

Deno.bench('old build', { baseline: true }, async () => {
	await new Deno.Command('deno', {
		args: ['task', 'run', 'build'],
		cwd: path.resolve(import.meta.dirname ?? '', '../<path_to_git_worktree_at_main_branch>'),
	}).output();
});

Deno.bench('new build', { baseline: true }, async () => {
	await new Deno.Command('deno', {
		args: ['task', 'run', 'build'],
		cwd: path.resolve(import.meta.dirname ?? '', '../<path_to_git_worktree_at_pr_branch>'),
	}).output();
});
```

</details>

... but rather tries to make the codebase more maintainable down the line.

## Quick Overview of Build Strategy

The `build` routine takes a list of configs, each essentially maps templates to corresponding build targets. All configs share the same interface.

template-based-build-strategy

### CODE REVIEW

**Comment by 11bit** [comment]
In general, I like the idea of using templates. It should make it easier to add more build targets. 

One thing, could you please move snapshots back to their folder - it makes things easier to review.

**Comment by vnphanquang** [comment]
@11bit no problem. Do you prefer to co-locate the test file right next to source file as well? Although there are some tests that do not correspond to one specific source file so those will stay in the `tests` folder.

**Comment by 11bit** [comment]
Yep, I prefer to colocate them. Thanks!

**Comment by vnphanquang** [comment]
@11bit fixed via https://github.com/evilmartians/harmony/pull/16/commits/6091caf63c69f05e3e3397eb550469d6fd7fef7d. Let me know if that's good. Thanks a lot!

**Review by 11bit — APPROVED** [review]
Very nice. Thank you @vnphanquang !

**Pull request merged**
